- id: open_blind_at_dawn
  alias: "Открыть штору на рассвете"
  mode: single
  trigger:
    - platform: time
      at: sensor.weather_sun_next_dawn
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: close_blind_morning
  alias: "Закрыть штору утром"
  mode: single
  trigger:
    - platform: time
      at: "10:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: numeric_state
      entity_id: sensor.weather_waqi_temperature
      below: 15
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: close_blind_evening
  alias: "Закрыть штору вечером"
  mode: single
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: numeric_state
      entity_id: sensor.weather_waqi_temperature
      below: 15
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: start_eddie_sleep
  alias: Укладываем Эди спать по расписанию
  mode: single
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
  action:
    action: script.prepare_eddie_for_sleep

- id: turn_off_on_leaving
  alias: Выключить всё, когда все ушли
  trigger:
    - platform: template
      value_template: >
        {{ states.person | selectattr('state', 'eq', 'home') | list | count == 0 }}
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.guests
      state: "off"
  action:
    - service: script.turn_on
      target:
        entity_id: script.turn_off_everything

- id: notify_cleaning_finished
  alias: Уведомить о завершении уборки
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_roborock_q7
      from: "cleaning"
      to: "docked"
  condition:
    - condition: state
      entity_id: input_boolean.notifications
      state: "on"
  action:
    - service: notify.notify
      data:
        title: Робот-пылесос
        message: "Закончил уборку"

- id: notify_door_opened
  alias: Уведомить об открытии двери
  trigger:
    - platform: state
      entity_id: binary_sensor.door_ikea_main_contact
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.notifications
      state: "on"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: person.andrey_sitnik
              state: "not_home"
          sequence:
            - service: notify.mobile_app_atocha
              data:
                title: "Дверь"
                message: "Открыта"
        - conditions:
            - condition: state
              entity_id: person.ekaterina_sitnik
              state: "not_home"
          sequence:
            - service: notify.mobile_app_pixel_7a
              data:
                title: "Дверь"
                message: "Открыта"
      default: []

- id: water_leak_bathroom
  alias: Уведомить о протечке воды в ванной
  trigger:
    - platform: state
      entity_id: binary_sensor.water_ikea_bathroom_water_leak
      from: "off"
      to: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.alert
    - service: notify.notify
      data:
        title: Ванная
        message: Протечка воды

- id: water_leak_washing_machine
  alias: Уведомить о протечке воды от стиральной машины
  trigger:
    - platform: state
      entity_id: binary_sensor.water_ikea_washing_machine_water_leak
      from: "off"
      to: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.alert
    - service: notify.notify
      data:
        title: Стиральная машина
        message: Протечка воды

- id: mark_vacuum_started_today
  alias: Отметить, что пылесос был запущен сегодня
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_roborock_q7
      from: "docked"
      to: "cleaning"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_was_run_today

- id: reset_vacuum_started_today
  alias: Сбросить отметку о запуске пылесоса сегодня
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_was_run_today

- id: daily_vacuum_on_leaving
  alias: Ежедневная уборка пылесосом когда все ушли
  trigger:
    - platform: template
      value_template: >
        {{ states.person | selectattr('state','eq','home') | list | count == 0 }}
  condition:
    - condition: state
      entity_id: input_boolean.vacuum_was_run_today
      state: "off"
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
  action:
    - service: vacuum.start
      target:
        entity_id: vacuum.vacuum_roborock_q7

- id: kitchen_light_on_motion
  alias: Включить свет на кухне при движении
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_tuya_kitchen_presence
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.presence_tuya_kitchen_illuminance
          below: 100
        - condition: time
          after: "sensor.weather_sun_next_rising"
          before: "sensor.weather_sun_next_rising"
  action:
    - service: light.turn_on
      target:
        entity_id: light.light_group_kitchen
    - wait_for_trigger:
        trigger: state
        entity_id: binary_sensor.presence_tuya_kitchen_presence
        from: "on"
        to: "off"
    - action: light.turn_off
      target:
        entity_id: light.light_group_kitchen
