- id: open_blind_dawn
  alias: "Открыть штору на рассвете"
  mode: single
  trigger:
    - platform: time
      at: sensor.weather_sun_next_dawn
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: close_blind_morning
  alias: "Закрыть штору утром"
  mode: single
  trigger:
    - platform: time
      at: "10:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: numeric_state
      entity_id: sensor.weather_waqi_temperature
      below: 15
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: close_blind_evening
  alias: "Закрыть штору вечером"
  mode: single
  trigger:
    - platform: time
      at: "19:40:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: numeric_state
      entity_id: sensor.weather_waqi_temperature
      below: 15
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.blind_ikea_bedroom

- id: start_eddie_sleep
  alias: Укладываем Эди спать по расписанию
  mode: single
  trigger:
    - platform: time
      at: "19:40:00"
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
  action:
    action: script.prepare_eddie_for_sleep

- id: turn_off_on_leaving
  alias: Выключить всё, когда все ушли
  trigger:
    - platform: template
      value_template: >
        {{ states.person | selectattr('state', 'eq', 'home') | list | count == 0 }}
  condition:
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.guests
      state: "off"
  action:
    - service: script.turn_on
      target:
        entity_id: script.turn_off_everything

- id: notify_door_opened
  alias: Уведомить об открытии двери
  trigger:
    - platform: state
      entity_id: binary_sensor.door_ikea_main_contact
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.notifications
      state: "on"
  action:
    - delay: "00:01:00"
    - choose:
        - conditions:
            - condition: state
              entity_id: person.andrey_sitnik
              state: "not_home"
          sequence:
            - service: notify.mobile_app_atocha
              data:
                title: "Дверь"
                message: "Открыта"
        - conditions:
            - condition: state
              entity_id: person.ekaterina_sitnik
              state: "not_home"
          sequence:
            - service: notify.mobile_app_pixel_7a
              data:
                title: "Дверь"
                message: "Открыта"
      default: []

- id: water_leak_bathroom
  alias: Уведомить о протечке воды в ванной
  trigger:
    - platform: state
      entity_id: binary_sensor.water_ikea_bathroom_water_leak
      from: "off"
      to: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.alert
    - service: notify.notify
      data:
        title: Ванная
        message: Протечка воды

- id: water_leak_washing_machine
  alias: Уведомить о протечке воды от стиральной машины
  trigger:
    - platform: state
      entity_id: binary_sensor.water_ikea_washing_machine_water_leak
      from: "off"
      to: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.alert
    - service: notify.notify
      data:
        title: Стиральная машина
        message: Протечка воды

- id: notify_cleaning_started
  alias: Уведомить о начале уборки
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_roborock_q7_max
      to: "cleaning"
  condition:
    - condition: state
      entity_id: input_boolean.notifications
      state: "on"
  action:
    - service: notify.notify
      data:
        title: Робот-пылесос
        message: "Начал уборку"

- id: notify_cleaning_finished
  alias: Уведомить о завершении уборки
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_roborock_q7_max
      from:
        - "cleaning"
        - "returning"
        - "emptying_the_bin"
      to: "docked"
  condition:
    - condition: state
      entity_id: input_boolean.notifications
      state: "on"
  action:
    - service: notify.notify
      data:
        title: Робот-пылесос
        message: "Закончил уборку"

- id: mark_vacuum_started_today
  alias: Отметить, что пылесос был запущен сегодня
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_roborock_q7_max
      from: "docked"
      to: "cleaning"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_was_run_today

- id: reset_vacuum_started_today
  alias: Сбросить отметку о запуске пылесоса сегодня
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_was_run_today

- id: daily_vacuum_on_leaving
  alias: Ежедневная уборка пылесосом когда все ушли
  trigger:
    - platform: template
      value_template: >
        {{ states.person | selectattr('state','eq','home') | list | count == 0 }}
  condition:
    - condition: state
      entity_id: input_boolean.vacuum_was_run_today
      state: "off"
    - condition: state
      entity_id: input_boolean.stop
      state: "off"
    - condition: state
      entity_id: input_boolean.cat_alone
      state: "off"
    - condition: time
      after: "08:40:00"
      before: "22:00:00"
  action:
    - service: vacuum.start
      target:
        entity_id: vacuum.vacuum_roborock_q7_max

- id: kitchen_light_on_motion
  alias: Включить свет на кухне при движении
  use_blueprint:
    path: presence.yaml
    input:
      presence_sensor: binary_sensor.presence_tuya_kitchen_presence
      light:
        entity_id: light.light_group_kitchen

- id: kitchen_wall_switch_buttons
  alias: Управление светом на кухне с помощью выключателя
  use_blueprint:
    path: wall-switch.yaml
    input:
      wall_switch: 4b07057170cdb07b760d2f31a4e0e5a5
      light: light.light_group_kitchen
      room: kitchen
      scene_helper: input_number.kitchen_last_scene

- id: lounge_wall_switch_buttons
  alias: Управление светом в зале с помощью выключателя
  use_blueprint:
    path: wall-switch.yaml
    input:
      wall_switch: 3f13b7a4f814bac7b7f94f4a68a4aee1
      light: light.light_aqara_t2_e27_rgb_lounge
      room: lounge
      scene_helper: input_number.lounge_last_scene

- id: bathroom_wall_switch_buttons
  alias: Управление светом в ванной с помощью выключателя
  use_blueprint:
    path: wall-switch.yaml
    input:
      wall_switch: e0f9d156e55b2a79a46d334c2522d795
      light: light.light_group_bathroom
      room: bathroom
      scene_helper: input_number.bathroom_last_scene
      extra_on:
        - action: switch.turn_on
          target:
            entity_id: switch.wall_switch_yandex_bathroom_1
      extra_off:
        - action: switch.turn_off
          target:
            entity_id: switch.wall_switch_yandex_bathroom_1

- id: bathroom_light_on_motion
  alias: Включить свет в ванной при движении
  use_blueprint:
    path: presence.yaml
    input:
      presence_sensor: binary_sensor.presence_tuya_bathroom_presence
      light:
        entity_id: light.light_group_bathroom
      extra_off:
        - action: switch.turn_off
          target:
            entity_id: switch.wall_switch_yandex_bathroom_1

- id: toilet_light_on_motion
  alias: Включить свет в туалете при движении
  use_blueprint:
    path: presence.yaml
    input:
      presence_sensor: binary_sensor.presence_tuya_toilet_presence
      light:
        entity_id: light.light_ikea_gu10_toilet

- id: adaptive_lights_sync
  alias: Управление сменой цвета ламп при переключении автоматизации
  trigger:
    - platform: state
      entity_id: input_boolean.stop
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.stop
              state: "on"
          sequence:
            - service: script.turn_on
              target:
                entity_id: switch.adaptive_lighting_integration_adaptive_lights
        - conditions:
            - condition: state
              entity_id: input_boolean.stop
              state: "off"
          sequence:
            - service: script.turn_off
              target:
                entity_id: switch.adaptive_lighting_integration_adaptive_lights

- id: night_mode_enable
  alias: Включить ночной режим
  mode: single
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.adaptive_lighting_sleep_mode_integration_adaptive_lights

- id: night_mode_disable
  alias: Выключить ночной режим
  mode: single
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.adaptive_lighting_sleep_mode_integration_adaptive_lights

- id: low_battery_notify
  alias: Уведомить о разряде батареи
  variables:
    threshold: 30
    sensors: >-
      {% set result = namespace(sensors=[]) %}
      {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
        {% if 0 <= state.state | int(-1) < threshold | int %}
          {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] %}
        {% endif %}
      {% endfor %}
      {{result.sensors|join(', ')}}
  mode: single
  trigger:
    - platform: time
      at: "10:00:00"
  condition:
    - "{{ sensors != '' }}"
  action:
    - service: notify.mobile_app_atocha
      data:
        title: "Дом"
        message: "Садиться батарея: {{ sensors }}"
