blueprint:
  name: Выключатель
  description: Логика работы настенных выключателей с 4 кнопками
  domain: automation
  input:
    wall_switch:
      name: ID устройства
      selector:
        device:
          integration: mqtt
          manufacturer: Yandex
    light:
      name: Лампа для управления
      selector:
        entity:
          filter:
            domain: light
    extra_on:
      name: Дополнительное действие при включении
      selector:
        action: {}
      default: []
    extra_off:
      name: Дополнительное действие при выключении
      selector:
        action: {}
      default: []
    room:
      name: Код комнаты
      selector:
        text:
    scene_helper:
      name: "Индекс сцены"
      selector:
        entity:
          domain: input_number

mode: queued

triggers:
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: toggle_b1_up
    id: turn_on
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: toggle_b1_down
    id: turn_off
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: toggle_b2_up
    id: brighter
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: toggle_b2_down
    id: darker
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: on_b2_up
    id: fast_brighter
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: on_b2_down
    id: fast_darker
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: off_b2_up
    id: full_brighter
  - platform: device
    device_id: !input wall_switch
    domain: mqtt
    type: action
    subtype: off_b2_down
    id: full_darker

variables:
  current_room: !input room
  current_scene_helper: !input scene_helper
  matched_scenes: >
    {{ states.scene
      | selectattr('entity_id','match','^scene\\.' ~ current_room)
      | map(attribute='entity_id')
      | sort
      | list }}
  current_scene_index: "{{ states[current_scene_helper].state | int }}"
  next_scene_index: >
    {% set length = matched_scenes | length %}
    {% if length == 0 %}
      -1
    {% else %}
      {{ (current_scene_index + 1) % length }}
    {% endif %}

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "on"
                sequence:
                  - choose:
                      - conditions: "{{ next_scene_index == -1 }}"
                        sequence:
                          - service: notify.mobile_app_atocha
                            data:
                              title: "Отладка"
                              message: >
                                No scenes found for room {{ current_room }}
                      - conditions: "{{ next_scene_index != -1 }}"
                        sequence:
                          - service: input_number.set_value
                            data:
                              entity_id: !input scene_helper
                              value: "{{ next_scene_index }}"
                          - service: scene.turn_on
                            data:
                              entity_id: "{{ matched_scenes[next_scene_index] }}"
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "off"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light
                  - sequence: !input extra_on

      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "on"
                sequence:
                  - action: light.turn_off
                    target:
                      entity_id: !input light
                  - sequence: !input extra_off
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "off"
                sequence:
                  - service: scene.turn_on
                    data:
                      entity_id: >
                        {{ 'scene.' ~ current_room ~ '_night' }}

      - conditions:
          - condition: trigger
            id: brighter
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "on"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light
                    data:
                      brightness_step_pct: 10
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "off"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light
                  - sequence: !input extra_on

      - conditions:
          - condition: trigger
            id: fast_brighter
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: 20

      - conditions:
          - condition: trigger
            id: full_brighter
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_pct: 100

      - conditions:
          - condition: trigger
            id: darker
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "on"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: !input light
                    data:
                      brightness_step_pct: -10
              - conditions:
                  - condition: state
                    entity_id: !input light
                    state: "off"
                sequence:
                  - service: scene.turn_on
                    data:
                      entity_id: >
                        {{ 'scene.' ~ current_room ~ '_night' }}

      - conditions:
          - condition: trigger
            id: fast_darker
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: -20

      - conditions:
          - condition: trigger
            id: full_darker
          - condition: state
            entity_id: !input light
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_pct: 1

    default: []
