frontend:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.50.27:1883
  user: home
serial:
  port: tcp://192.168.50.27:6638
  baudrate: 115200
  adapter: ember
  rtscts: false
advanced:
  channel: 25
homeassistant:
  enabled: true
version: 4
devices:
  "0xec1bbdfffed34bcd":
    friendly_name: light.andrey_room.top
