name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Print Podman versions
        run: podman -v
      - name: Fake Docker Hub auth
        run: echo "{}" > units/dockerhub/docker-auth.json
      - name: Fake dhparam.pem
        run: echo "" > units/domains/dhparam.pem
      - name: Run tests
        run: make test
      - name: Print Butane config
        run: cat ./config.bu
